Team4_maimai-master/MaiMai/MaiMai/Controllers/MyAccountController.cs
using MaiMai.Models;
using MaiMai.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MaiMai.Controllers
{
    public class MyAccountController : Controller
    {
        // GET: MyAccount
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult myAccountIndex()
        {
            return View();
        }

        maimaiEntities db = new maimaiEntities();

        public ActionResult getAccount_P()
        {
            var userName = Request.Cookies["LoginName"].Value.ToString();
            if (userName == null)
                return Content("尚未登入");
            var getAccount = db.Member.Where(m => m.userAccount == userName).Select(s => new MemberViewModel()
            {
                ProImg = s.ProImg,
                connectionID = s.connectionID,
                UserID = s.UserID,
                userAccount = s.userAccount,
                userPassWord = s.userPassWord,
                city = s.city,
                address = s.address,
                phoneNumber = s.phoneNumber,
                firstName = s.firstName,
                lastName = s.lastName,
                birthday = s.birthday,
                identityNumber = s.identityNumber,
                profileImg = s.profileImg,
                userLevel = s.userLevel,
                totalStarRate = s.totalStarRate,
                selfDescription = s.selfDescription,
                email = s.email
            }).ToList();

            return Json(getAccount, JsonRequestBehavior.AllowGet);
        }
        maimaiRepository<Member> mb = new maimaiRepository<Member>();

        [HttpPost]
        public ActionResult editMember_P(Member mem)
        {
            mb.Update(mem);

            return Content("修改成功");
        }

        public ActionResult MyAccount()
        {
            return View();
        }
        public ActionResult MyPassword()
        {
            return View();
        }

        public String Editpassword(LoginViewModel password)
        {
            Member mb1 = db.Member.FirstOrDefault(m => m.userAccount == password.userAccount && m.userPassWord == password.userPassWord);
            if (mb1 == null)
            {
                return "帳號不存在或密碼錯誤!";
            }

           

            return "登入成功";
        }
        public string Doingmember(MemberViewModel mber)
        {
          
            Member memmgg = new Member()
            {
                UserID = mber.UserID,

                userAccount = mber.userAccount,

                city = mber.city,
                address = mber.address,
                phoneNumber = mber.phoneNumber,
                //profileImg = mber.upphoto.FileName,
                
                firstName = mber.firstName,
                lastName = mber.lastName,
                selfDescription = mber.selfDescription,
                email = mber.email,

                identityNumber = mber.identityNumber,
                userLevel = mber.userLevel,
                totalStarRate = mber.totalStarRate,
                ProImg = mber.ProImg,
                connectionID = mber.connectionID,
                userPassWord = mber.userPassWord,
                birthday = mber.birthday,


                 
                
            };
            if (mber.upphoto == null)
            {
                var mbb = db.Member.FirstOrDefault(a => a.UserID == mber.UserID);
                memmgg.profileImg = mbb.profileImg;
            }
            else
            {
                

                memmgg.profileImg = mber.upphoto.FileName;
                string filename = mber.upphoto.FileName;
                mber.upphoto.SaveAs(Server.MapPath("../Content/ProductPostImg/member/") + filename);
                string filePath = $"../Content/ProductPostImg/member/{filename}";

            }
            //HttpPostedFileBase photo = new HttpPostedFileBase(upphoto);




            mb.Update(memmgg);
            return "註冊成功";



        }



    }
}

Team4_maimai-master/MaiMai/MaiMai/Views/MyAccount/MyPassword.cshtml
@{
    ViewBag.Title = "MyPassword";
    Layout = "~/Views/Shared/_Layoutmaimai.cshtml";
}


 
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <link href="~/Content/cssCHIEN/MyAccount.css" rel="stylesheet" />
    <style>
        .abc87 {
            position: absolute;
            top: 0;
            right:0;
            padding: 0 4px;
            pointer-events: none;
            background: #fff;
            -webkit-transition: font-size .25s ease,-webkit-transform .25s ease;
            transition: font-size .25s ease,-webkit-transform .25s ease;
            transition: transform .25s ease,font-size .25s ease;
            transition: transform .25s ease,font-size .25s ease,-webkit-transform .25s ease;
            -webkit-transform: translateY(-50%);
            transform: translateY(-50%);
        }
        .D_cm {
            font-weight: 400;
        }

        .D_bU {
            color: #2c2c2d;
        }

        .D_bY1 {
            color: #008f79;
        }
        .bigg12 {
            font-weight: 600;
        }

    </style>
</head>

<body>


    <div class="D_PC D_bs M_tG D_bo" style="padding-bottom:0px;padding-top:104px;">

        <div class="D_PE">
            <div class="D_PF">
                <div class="D_ui M_kh D_uj M_ki  D_oz">
                    <a class="D_ul M_kk D_tA D_un M_km   M_ko D_gN M_fQ"
                       href="/MyAccount/MyAccount">
                        <p class=" greenline D_bO M_bF D_bU M_bL D_ca M_bR D_ce M_bU D_cg M_bW D_ci M_bY   M_cc D_tB D_bH">
                            編輯檔案
                        </p>
                    </a>
                    <a class=" D_up D_ul M_kk D_tA D_gN M_fQ" href="/MyAccount/MyPassword">
                        <p class="D_bO M_bF D_bY1 M_bP D_ca M_bR D_ce M_bU D_cg M_bW D_ci M_bY D_cl M_cb D_tB D_bH  bigg12">
                            更改密碼
                        </p>
                    </a>
                    @*<a class="D_ul M_kk D_tA D_gN M_fQ" href="/settings/data-and-privacy">
                        <p class="D_bO M_bF D_bY M_bP D_ca M_bR D_ce M_bU D_cg M_bW D_ci M_bY D_cl M_cb D_tB D_bH">
                            數據和隱私
                        </p>
                    </a>*@
                </div>
            </div>
            <div class="D_PG" id="account">
                @*<div class="D_PZ D_bx D_bz">
                        <div class="D_Qa">
                            <h1 class="D_eA D_eJ D_eM D_eP D_eS D_cV">更改密碼</h1>
                        </div>
                        <form>
                            <div class="D_jo D_Qe">
                                <div class="D_jp D_iY">
                                    <div class="D_jr">
                                        <span class="D_bO D_bY D_ca D_ce D_cg D_cj D_cl D_jt D_jc D_bH">目前密碼</span>
                                        <input aria-label="目前密碼" autocomplete="off" class="D_ju D_jh" type="password" id="userPassWordOk">
                                    </div>
                                </div>
                            </div>
                            <div class="D_jo D_Qe">
                                <div class="D_jp D_iY">
                                    <div class="D_jr">
                                        <span class="D_bO D_bY D_ca D_ce D_cg D_cj D_cl D_jt D_jc D_bH">新密碼</span><input aria-label="新密碼" autocomplete="off" class="D_ju D_jh"   id="userPassWord" name="userPassWord" type="password">
                                    </div>
                                </div>
                            </div>
                            <div class="D_jo D_Qe">
                                <div class="D_jp D_iY">
                                    <div class="D_jr">
                                        <span class="D_bO D_bY D_ca D_ce D_cg D_cj D_cl D_jt D_jc D_bH">確認新密碼</span><input aria-label="確認新密碼" autocomplete="off" class="D_ju D_jh"     type="password" id="userPassWordcheck">
                                    </div>
                                </div>
                            </div>
                            <div class="D_Qb"></div><button class="D_cY D_et D_em D_ea D_eu D_Qc"     type="button">
                                儲存更改
                            </button>
                        </form>
                    </div>
                </div>*@
            </div>
        </div>

    </div>




    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>
    <script>





        $(function () {
            $(".greenline").hover(function () {
                $(".greenline").css("color", "green")
            }, function () {
                $(".greenline").css("color", "black");
            });
        $.ajax({
            url: "@Url.Action("getAccount_P", "MyAccount")",
            type: "GET",
            success: function (account) {

                $(account).each(function (index, mem) {
                    console.log(mem.selfDescription)
                    var Milliseconds = parseInt(mem.birthday.replace(/\D/igm, ""));
                    var year = new Date(Milliseconds).getFullYear();
                    var month = new Date(Milliseconds).getMonth() + 1;
                    var date = new Date(Milliseconds).getDate();
                    $("#account").html(`
                   <div class="D_PZ D_bx D_bz">
                        <div class="D_Qa">
                            <h1 class="D_eA D_eJ D_eM D_eP D_eS D_cV">更改密碼</h1>
                        </div>
                        <form>
                            <div class="D_jo D_Qe">
                                <div class="D_jp D_iY">
                                    <div class="D_jr">
                                        <span class="D_bO D_bY D_ca D_ce D_cg D_cj D_cl D_jt D_jc D_bH">目前密碼</span><span id="rightman"  class="abc87 D_bO D_bY D_ca D_ce D_cg D_cj D_cl   D_jc D_bH" style="color: #57585a">請輸入正確的密碼以繼續</span>
                                        <input aria-label="目前密碼" autocomplete="off" onblur="passPassword()" class="D_ju D_jh" type="password" id="userPassWordOk">
                                        
                                    </div> 
                                </div>
                            </div>
                            <div class="D_jo D_Qe">
                                <div class="D_jp D_iY">
                                    <div class="D_jr">
                                        <span class="D_bO D_bY D_ca D_ce D_cg D_cj D_cl D_jt D_jc D_bH">新密碼</span><input aria-label="新密碼" autocomplete="off" class="D_ju D_jh"   id="userPassWord" name="userPassWord" type="password">
                                    </div>
                                </div>
                            </div>
                            <div class="D_jo D_Qe">
                                <div class="D_jp D_iY">
                                    <div class="D_jr">
                                        <span class="D_bO D_bY D_ca D_ce D_cg D_cj D_cl D_jt D_jc D_bH">確認新密碼</span><input aria-label="確認新密碼" autocomplete="off" class="D_ju D_jh"     type="password" id="userPassWordcheck">
                                    </div>
                                </div>
                            </div>
<input type="text" class="form-control" name="profileImg" hidden    value="${mem.profileImg}" />
 <input type="text" class="form-control" name="userAccount" id="checkUserAccount" hidden value="${mem.userAccount}" />
<input type="text" class="form-control" name="firstName" hidden value="${mem.firstName}" />
<input type="text" class="form-control" name="lastName" hidden value="${mem.lastName}" />
 <input type="text" class="form-control" name="selfDescription" hidden value="${mem.selfDescription}" />
   <input type="text" class="form-control" name="city" hidden  value="${mem.city}" />
<input type="text" class="form-control" name="address" hidden  value="${mem.address}" />
<input type="text" class="form-control" name="phoneNumber" hidden value="${mem.phoneNumber}" />
 <input type="text" class="form-control" name="email" hidden  value="${mem.email}"/>
<input name="UserID" hidden value="${mem.UserID}"/>
<input type="text" hidden class="form-control" name="birthday" value="${year}-${month}-${date}" />
<input name="userLevel" hidden value="${mem.userLevel}"/>
  <input hidden value="${mem.userPassWord}"    id="pwd"/>
<input type="text" class="form-control" name="identityNumber" hidden   value="${mem.identityNumber}" />

<input type="text" class="form-control" name="connectionID" hidden    value="${mem.connectionID}" />
<input type="text" class="form-control" name="totalStarRate"hidden  value="${mem.totalStarRate}" />
<input type="text" class="form-control" name="ProImg"hidden  value="${mem.ProImg}" />

                            <div class="D_Qb"></div><button class="D_cY D_et D_em D_ea D_eu D_Qc"  id="key1" disabled="true" onclick="editMember()"  type="button">
                                更改密碼
                            </button>
                        </form>
                    </div>

                `)
                })
            },
            error: function () {
                window.location.href = "../../Members/Login";
            }
        })











        })
         function passPassword() {
             var checkpassword = $("#userPassWordOk").val();
            var checkUserAccount2 = $("#checkUserAccount").val();
            $.ajax({

              url: "@Url.Action("Editpassword", "MyAccount")",
                type: "POST",
                data: {
                    userPassWord: checkpassword,
                    userAccount: checkUserAccount2


                },
                success: function (data) {

                    var byebye = data.indexOf("密碼錯誤")
                    if (byebye < 0) {
                        $('#rightman').css("color", "green")
                        $('#rightman').html("密碼正確，請繼續更改密碼")

                        $('#key1').attr('disabled', false);
                        //alert(data);
                        //alertTest1()
                        //window.location.href = "/NewMaimaiIndex/MaimaiIndexNew";
                        //setTimeout("home()", 2000)
                    }
                    else {
                        $('#rightman').css("color", "red")
                        $('#rightman').html("您所輸入的密碼錯誤")
                        $('#key1').attr('disabled', true);

                        //alertTest()
                    }


                }

            })

        }



        function bad() {
            Swal.fire(
                "請輸入您要修改的密碼", //標題
                "", //訊息內容(可省略)
                "error" //圖示(可省略) success/info/warning/error/question
            );
        }
        function bad2() {
            Swal.fire(
                "新密碼驗證失敗", //標題
                " 請檢查兩次密碼輸入是否相同", //訊息內容(可省略)
                "error" //圖示(可省略) success/info/warning/error/question
            );
        }

        function okok() {
            Swal.fire(
                "新密碼修改成功", //標題
                "盡情使用MaiMai買買吧!", //訊息內容(可省略)
                "success" //圖示(可省略) success/info/warning/error/question
            );
        }
        function editMember() {

            if ($("#userPassWord").val() == "" && $("#userPassWordcheck").val() == "") {
                //var oldPwd = $("#pwd").val();
                //var test = $("#userPassWord").val(`${oldPwd}`);
                bad()
                return false;
            }
            else if ($("#userPassWord").val() != $("#userPassWordcheck").val()) {
                bad2()
                return false;
            }

            var form = document.querySelector("form");
            var formdata = new FormData(form);
            console.log(formdata);
            console.log(form);
            $.ajax({
                url: "@Url.Action("editMember_P", "MyAccount")",
                type: "POST",
                data: formdata,
                processData: false,
                contentType: false,
                success: function (account) {
                    //$("#userPassWord").val("")
                    okok()
                }
                })

        }
    </script>
</body>

</html>

Team4_maimai-master/MaiMai/MaiMai/Views/MyAccount/myAccountIndex.cshtml
@{
    ViewBag.Title = "myAccountIndex";
}


<div class="container" style="padding-top:100px">
    <div class="row">

        <div id="account"></div>
        @*<form>
            <input name="UserID" hidden value="${mem.UserID}"/>
            <input name="userLevel" hidden value="${mem.userLevel}"/>
            <label>帳號</label>
            <input type="text" class="form-control" name="UserAccount" value="${mem.Account}" />
            <label>新密碼</label>
            <input required type="text" class="form-control" name="userPassWord" id="userPassWord" />
            <label>確認新密碼</label>
            <input required type="text" class="form-control" id="userPassWordcheck" />
            <label>城市</label>
            <input type="text" class="form-control" name="city" value="${mem.city}" />
            <label>地址</label>
            <input type="text" class="form-control" name="address" value="${mem.address}" /> 
            <label>手機號碼</label>
            <input type="text" class="form-control" name="phoneNumber" value="${mem.phoneNumber}" />
            <label>名字</label>
            <input type="text" class="form-control" name="firstName" value="${mem.firstName}" />
            <label>姓氏</label>
            <input type="text" class="form-control" name="lastName" value="${mem.lastName}" />
            <label>生日</label>
            <input type="text" class="form-control" name="birthday" value="${mem.birthday}" />
            <label>身分證字號</label>
            <input type="text" class="form-control" name="identityNumber" value="${mem.identutyNumber}" />
            <label>個人頭像</label>
            <input type="text" class="form-control" name="profileImg" value="${mem.profileImg}" />
            <label>個人簡介</label>
            <input type="text" class="form-control" name="selfDescription" value="${mem.selfDescription}" />
            <label>信箱</label>
            <input type="text" class="form-control" name="email" value="${mem.email}"/>
            <a class="btn btn-warning mt-3">修改</a>            
        </form>*@
       
    </div>
</div>


<script>
    $(function () {
        $.ajax({
            url: "@Url.Action("getAccount_P", "MyAccount")",
            type: "GET",
            success: function (account) {
                $(account).each(function (index, mem) {
                    var Milliseconds = parseInt(mem.birthday.replace(/\D/igm, ""));
                    var year = new Date(Milliseconds).getFullYear();
                    var month = new Date(Milliseconds).getMonth() + 1;
                    var date = new Date(Milliseconds).getDate();
                    $("#account").html(`
                    <form>
            <input name="UserID" hidden value="${mem.UserID}"/>
            <input name="userLevel" hidden value="${mem.userLevel}"/>
            <input hidden value="${mem.userPassWord}" id="pwd"/>
            <label>帳號</label>
            <input type="text" class="form-control" name="UserAccount" readonly value="${mem.userAccount}" />
            <label>新密碼</label>
            <input required type="text" class="form-control" name="userPassWord" id="userPassWord" />
            <label>確認新密碼</label>
            <input required type="text" class="form-control" id="userPassWordcheck" />
            <label>城市</label>
            <input type="text" class="form-control" name="city" value="${mem.city}" />
            <label>地址</label>
            <input type="text" class="form-control" name="address" value="${mem.address}" />
            <label>手機號碼</label>
            <input type="text" class="form-control" name="phoneNumber" value="${mem.phoneNumber}" />
            <label>名字</label>
            <input type="text" class="form-control" name="firstName" value="${mem.firstName}" />
            <label>姓氏</label>
            <input type="text" class="form-control" name="lastName" value="${mem.lastName}" />
            <label>生日</label>
            <input type="text" class="form-control" name="birthday" value="${year}-${month}-${date}" />
            <label>身分證字號</label>
            <input type="text" class="form-control" name="identityNumber" readonly value="${mem.identityNumber}" />
            <label>個人頭像</label>
            <input type="text" class="form-control" name="profileImg" value="${mem.profileImg}" />
            <label>個人簡介</label>
            <input type="text" class="form-control" name="selfDescription" value="${mem.selfDescription}" />
            <label>信箱</label>
            <input type="text" class="form-control" name="email" value="${mem.email}"/>
            <a class="btn btn-warning mt-3" onclick="editMember()">修改</a>
        </form>
                `)
                })
            },
            error: function () {
                window.location.href = "../../Members/Login";
            }
        })
    })
        function editMember() {

            if ($("#userPassWord").val() == "" && $("#userPassWordcheck").val() == "") {
                var oldPwd = $("#pwd").val();
                var test = $("#userPassWord").val(`${oldPwd}`);
            }
            else if ($("#userPassWord").val() != $("#userPassWordcheck").val()) {
                alert("新密碼驗證失敗")
                return false;
            }

            var form = document.querySelector("form");
            var formdata = new FormData(form);
            console.log(formdata);
            console.log(form);
            $.ajax({
                url: "@Url.Action("editMember_P", "MyAccount")",
                type: "POST",
                data: formdata,
                processData: false,
                contentType: false,
                success: function (account) {
                    $("#userPassWord").val("")
                        alert("修改成功")
                }
                })

        }
    
</script>