Team4_maimai-master/MaiMai/MaiMai/Models/Comment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaiMai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public Nullable<int> OrderdetalID { get; set; }
        public Nullable<double> starRate { get; set; }
        public string commentDescription { get; set; }
        public int UserID { get; set; }
        public Nullable<int> CommentorUserID { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    }
}

Team4_maimai-master/MaiMai/MaiMai/Models/Report.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaiMai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportID { get; set; }
        public int reportorID { get; set; }
        public int repotedUserID { get; set; }
        public Nullable<int> reportStatus { get; set; }
        public Nullable<System.DateTime> createdTime { get; set; }
        public Nullable<int> ReportDetailID { get; set; }
        public string reportDescription { get; set; }
        public int ProductOrRequire { get; set; }
        public int ProductOrRequireID { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual ReportDetail ReportDetail { get; set; }
    }
}

Team4_maimai-master/MaiMai/MaiMai/Models/ViewModel/CommentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MaiMai.Models.ViewModel
{
    public class CommentViewModel
    {

        public int CommentID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<double> starRate { get; set; }
        public string commentDescription { get; set; }
        public int UserID { get; set; }
        public Nullable<int> CommentorUserID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string profileImg { get; set; }
        public virtual Member Member { get; set; }
    }
}

Team4_maimai-master/MaiMai/MaiMai/Controllers/CommentController.cs
using MaiMai.Models;
using MaiMai.Models.ViewModel;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MaiMai.Controllers
{
    public class CommentController : Controller
    {
        // GET: Comment
        public ActionResult Comment()
        {
            return View();
        }

      
        maimaiEntities db = new maimaiEntities();
        public ActionResult ViewRate(int UserID)
        {


            var table = db.Comment.Where(m => m.CommentorUserID == UserID).Select(m => new CommentViewModel()
            {
                CommentID = m.CommentID,
                OrderID = m.OrderdetalID,
                starRate = m.starRate,
                commentDescription = m.commentDescription,
                UserID = m.UserID,
                CommentorUserID = m.CommentorUserID,
                profileImg = m.Member.profileImg,
                firstName = m.Member.firstName,
                lastName = m.Member.lastName
                //Member=m.Member.firstName,
            }).ToList();
            return Content(JsonConvert.SerializeObject(table), "application/json");

            //return Json(table, JsonRequestBehavior.AllowGet);
        }
        public ActionResult TotalStarRate(int UserID)
        {
            var a = db.Comment.Where(m => m.CommentorUserID == UserID).GroupBy(i => i.CommentorUserID).Select(g => new {

                RateCount = g.Count(),
                Average = g.Average(i => i.starRate),
                RateMax = g.Max(i => i.starRate)
            });


            return Content(JsonConvert.SerializeObject(a), "application/json");

            //return Json(table, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Comment_WithoutLogin()
        {
            return View();
        }
    }
}

Team4_maimai-master/MaiMai/MaiMai/Controllers/MyOrderController.cs
                     
//using AllPay.Payment.Integration;
using MaiMai.Models;
using MaiMai.Models.ViewModel;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace MaiMai.Controllers
{

    public class MyOrderController : Controller
    {
        // GET: backstage
        public ActionResult Index()
        {
            return View();
        }
        maimaiRepository<OrderDetail> odtail = new maimaiRepository<OrderDetail>();
        maimaiRepository<Member> mb = new maimaiRepository<Member>();
        maimaiRepository<Order> odRepository = new maimaiRepository<Order>();
        maimaiEntities db = new maimaiEntities();
        public ActionResult myOrder()
        {
            return View();
        }

        public ActionResult getMemberList_P()
        {

            var memList = db.Member.Select(m => new MemberViewModel()
            {
                UserID = m.UserID,
                userAccount = m.userAccount,
                userPassWord = m.userPassWord,
                city = m.city,
                address = m.address,
                phoneNumber = m.phoneNumber,
                firstName = m.firstName,
                lastName = m.lastName,
                Name = m.lastName + m.firstName,
                birthday = m.birthday,
                identityNumber = m.identityNumber,
                profileImg = m.profileImg,
                userLevel = m.userLevel,
                totalStarRate = m.totalStarRate,
                selfDescription = m.selfDescription,
                email = m.email,
                userLevelString = m.userLevel.ToString()
            });

            return Json(memList, JsonRequestBehavior.AllowGet);

        }

        public ActionResult getAdminList_P(int userLevel)
        {

            var memList = db.Member.Where(m => m.userLevel == userLevel).Select(m => new MemberViewModel()
            {
                UserID = m.UserID,
                userAccount = m.userAccount,
                userPassWord = m.userPassWord,
                city = m.city,
                address = m.address,
                phoneNumber = m.phoneNumber,
                firstName = m.firstName,
                lastName = m.lastName,
                Name = m.lastName + m.firstName,
                birthday = m.birthday,
                identityNumber = m.identityNumber,
                profileImg = m.profileImg,
                userLevel = m.userLevel,
                totalStarRate = m.totalStarRate,
                selfDescription = m.selfDescription,
                email = m.email,
                userLevelString = m.userLevel.ToString()
            }).ToList();

            return Json(memList, JsonRequestBehavior.AllowGet);

        }

        public ActionResult getMember_P(int? id)
        {
            if (id == null)
            {
                return Content("錯誤");
            }
            var mem = db.Member.Where(m => m.UserID == id).Select(m => new MemberViewModel()
            {
                UserID = m.UserID,
                userAccount = m.userAccount,
                userPassWord = m.userPassWord,
                city = m.city,
                address = m.address,
                phoneNumber = m.phoneNumber,
                Name = m.lastName + m.firstName,
                birthday = m.birthday,
                identityNumber = m.identityNumber,
                profileImg = m.profileImg,
                userLevel = m.userLevel,
                totalStarRate = m.totalStarRate,
                selfDescription = m.selfDescription,
                email = m.email,
                firstName = m.firstName,
                lastName = m.lastName,
                userLevelString = m.userLevel.ToString()
            }).ToList();

            return Json(mem, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult editUserLevel_P(Member m)
        {
            mb.Update(m);
            return Json(m, JsonRequestBehavior.AllowGet);
        }

        public ActionResult getOrderList_P(int? status)  //key group by
        {

            var id = Convert.ToInt32(Request.Cookies["LoginID"].Value); 
            if (status != null)
            {
                if (status >= 2)
                {
                    var ordercmplist = db.Order.Where(m => (m.orderStatus >= 2) && (m.buyerUserID == id)).Join(db.OrderDetail, x => x.OrderId, y => y.OrderID, (x, y) => new
                    {
                        x.OrderId,
                        x.orderStatus,
                        x.createdTime,
                        x.buyerUserID,
                        x.Member.firstName,
                        //y.SellerID,
                        y.oneProductTotalPrice,

                    }).GroupBy(g => new { g.OrderId, g.orderStatus, g.createdTime, g.buyerUserID, g.firstName }).Select(s => new
                    {
                        OrderId = s.Key.OrderId,
                        orderStatus = s.Key.orderStatus,
                        createdTime = s.Key.createdTime,
                        buyerUserID = s.Key.buyerUserID,
                        buyerName = s.Key.firstName,
                        //SellerID =s.Select(i => i.SellerID),
                        price = s.Select(i => i.oneProductTotalPrice).Sum(),
                    }) ;
                    return Json(ordercmplist, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var ordercmplist = db.Order.Where(m => (m.orderStatus < 2)&&(m.buyerUserID==id)).Join(db.OrderDetail, x => x.OrderId, y => y.OrderID, 
                        /*db.Order, x => x.OrderId -----db.OrderDetail,y=>y.OrderID兩張表單串聯*/
                        (x, y) => new{
                        x.OrderId,
                        x.orderStatus,
                        x.createdTime,
                        x.buyerUserID,
                        x.Member.firstName,
                        //y.SellerID,
                        y.oneProductTotalPrice,

                    }).GroupBy(g => new { g.OrderId, g.orderStatus, g.createdTime, g.buyerUserID, g.firstName }).Select(s => new
                    {
                        OrderId = s.Key.OrderId,
                        orderStatus = s.Key.orderStatus,
                        createdTime = s.Key.createdTime,
                        buyerUserID = s.Key.buyerUserID,
                        buyerName = s.Key.firstName,
                        //SellerID =s.Select(i => i.SellerID),
                        price = s.Select(i => i.oneProductTotalPrice).Sum()
                    });

                    return Json(ordercmplist, JsonRequestBehavior.AllowGet);
                }
            }

            var orderlist = db.Order.Join(db.OrderDetail, x => x.OrderId, y => y.OrderID, (x, y) => new
            {
                x.OrderId,
                x.orderStatus,
                x.createdTime,
                x.buyerUserID,
                x.Member.firstName,
                y.oneProductTotalPrice,

            }).GroupBy(g => new { g.OrderId, g.orderStatus, g.createdTime, g.buyerUserID, g.firstName }).Select(s => new
            {
                OrderId = s.Key.OrderId,
                orderStatus = s.Key.orderStatus,
                createdTime = s.Key.createdTime,
                buyerUserID = s.Key.buyerUserID,
                buyerName = s.Key.firstName,
                //SellerID =s.Select(i => i.SellerID),
                price = s.Select(i => i.oneProductTotalPrice).Sum()
            });

            return Json(orderlist, JsonRequestBehavior.AllowGet);
        }

        public ActionResult delOrder_P(int OrderId)
        {
            odRepository.Delete(OrderId);
            return Content("刪除成功");
        }

        public ActionResult getOrderDetail_P(int OrderId)
        {
            var orderDetail = db.OrderDetail.Where(o => o.OrderID == OrderId).Select(s => new
            {
                ProductPostID = s.ProductPostID,
                productName = s.ProductPost.productName,
                oneProductTotalPrice = s.QTY * s.ProductPost.price,
                QTY = s.QTY,
                createdTime = s.Order.createdTime,
                SellerName = s.ProductPost.Member.firstName
            }).ToList();

            return Json(orderDetail, JsonRequestBehavior.AllowGet);
        }

        public ActionResult getProduct_P(int? ProductPostID, int? QTY)
        {
            if (ProductPostID == null || QTY == null)
            {
                return Content("格式錯誤");
            }
            var product = db.ProductPost.Where(p => p.ProductPostID == ProductPostID).Select(s => new
            {
                ProductPostID = s.ProductPostID,
                productName = s.productName,
                productDescription = s.productDescription,
                productImg = s.productImg,
                UserName = s.Member.firstName,
                QTY = QTY,
                price = QTY * s.price,
                TagID = s.TagID,
                Tag = s.Tag.tagName,
                createdTime = s.createdTime

            }).ToList();

            return Json(product, JsonRequestBehavior.AllowGet);
        }


        public ActionResult report()
        {
            return View();
        }

        public ActionResult getReport(int ?postID)
        {
            var reportDetail = db.ReportDetail.Select(t => new
            {
                reason = t.reason
            }).ToList();

            return Json(reportDetail, JsonRequestBehavior.AllowGet);
        }


        maimaiRepository<Report> rtdb = new maimaiRepository<Report>();

        public ActionResult saveReport(string reportTXT, int reportTAG)
        {

            Report r = new Report
            {
                reportorID = 13,//Convert.ToInt32(Request.Cookies["LoginID"].Value),

Team4_maimai-master/MaiMai/MaiMai/Views/MyOrder/checkOut.cshtml
@{
    ViewBag.Title = "checkOut";
}

<h2>checkOut</h2>

@*harsh key*--5294y06JbISpM5x9
    Hash IV--v77hoKGq4kWxNNIS*@
@*<button class="btn btn-danger pt-5 mt-5" onclick="getFormData()">送出交易資料</button>*@

<div id="form" class="mt-5">

</div>

<script>

    $(function () {

                $.ajax({
            url: "@Url.Action("creditCardcheckOut", "MyOrder")",
            data: { OrderId:75},
            type: "GET",
                    success: function (result) {
                
                        var totalDollar = 0;
                        var MerchantTradeNo = 0;
                        var prodName ;
                        var tradeDescription='';
                        var format_time;
                        var CheckMacValue;
                        $.each(result, function (index, item) {

                            totalDollar = item.totalAmount;
                            prodName = item.ItemName;
                            tradeDescription =item.tradeDescription;
                            MerchantTradeNo = item.MerchantTradeNo;
                            format_time = item.MerchantTradeDate;
                            CheckMacValue = item.CheckMacValue;
                        }),
                            console.log("prodName", prodName);
                            console.log("tradeDescription", tradeDescription);
                            console.log("MerchantTradeNo", MerchantTradeNo);
                            console.log("format_time", format_time);

                        $("#form").append(`
<form id="formCreditCard" method="post" accept-charset="UTF-8"
 action="https://payment-stage.opay.tw/Cashier/AioCheckOut/V5" >

MerchantID 商店代號:
<input type="text" name="MerchantID" value="2000132" /><br />

MerchantTradeNo 商店交易編號:
<input type="text" name="MerchantTradeNo" value="${MerchantTradeNo}" /><br />

MerchantTradeDate 商店交易時間:
<input type="text" name="MerchantTradeDate" value="${format_time}" /><br />

PaymentType 交易類型:
<input type="text" name="PaymentType" value="aio" /><br />

TotalAmount 交易金額:
<input type="text" name="TotalAmount" value="${totalDollar}" /><br />

TradeDesc 交易描述:
<input type="text" name="TradeDesc" value="${tradeDescription}" /><br />

ItemName 商品名稱:
<input type="text" name="ItemName" value="${prodName}" /><br />

ReturnURL 付款完成通知回傳網址:
<input type="text" name="ReturnURL" value="https://localhost:44340/" /><br />

ChoosePayment 預設付款方式:
<input type="text" name="ChoosePayment" value="Credit" /><br />

會員商店代碼:
<input type="text" name="StoreID" value="" /><br />

ClientBackURL Client端返回廠商網址:
<input type="text" name="ClientBackURL" value="https://localhost:44340/" /><br />

CreditInstallment 刷卡分期期數:
<input type="text" name="CreditInstallment" value="" /><br />

InstallmentAmount 使用刷卡分期的付款金額:
<input type="text" name="InstallmentAmount" value="" /><br />

Redeem 信用卡是否使用紅利折抵:
<input type="text" name="Redeem" value="" /><br />

CheckMacValue 簽章類型:
<input type="text" name="EncryptType" value="1" /><br />

CheckMacValue 檢查碼:
<input type="text" name="CheckMacValue" value="${CheckMacValue}" /><br />

<input type="submit" value="送出訂單" />

</form>
                `)
        },
        //error:
        })
    });


</script>

Team4_maimai-master/MaiMai/MaiMai/Views/MyOrder/commentForm.cshtml
@{
    ViewBag.Title = "commentForm";
}
<style>
    img[src*="star"]{
        width:30px;
        margin:0 10px;
    }
</style>
<div class="container " style="padding-top:100px; ">

    <h2>commentForm</h2>

    <!-- Button trigger modal -->
    <button class="btn btn-warning" data-toggle="modal" onclick="getComment()" data-target="#exampleModalCenter">回饋單</button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title" id="exampleModalCenterTitle">評分與評論</h2>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span id="modalSpan" aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div id="modal-body" class="modal-body" style="margin-bottom:30px">
                    <div style="text-align:center" class="mb-5">
                        <img src="" />
                    
                    </div>
                    <h4>請問您對這次交易的滿意度為 :</h4>
                    <div id="div0" style="width:auto">
                        <img id="img0" src="../Content/ProductPostImg/member/star.jfif" />
                        <img id="img1" src="../Content/ProductPostImg/member/star.jfif" />
                        <img id="img2" src="../Content/ProductPostImg/member/star.jfif" />
                        <img id="img3" src="../Content/ProductPostImg/member/star.jfif" />
                        <img id="img4" src="../Content/ProductPostImg/member/star.jfif" />
                        <p>   </p>
                    </div>

                    <div style="border-bottom:solid 1px black" class=" pb-5 pt-3 mb-3">
                    <div class="progress " >
                        <div id="progress-bar" class="progress-bar progress-bar-striped bg-success " role="progressbar" style="width: 25%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5">25%.....
                        </div>
                    </div>
                    <span id="commentCNT">評分人數</span>
                    </div>

                    <div id="warning" class="align-content-center mt-5">
                        <label>內容描述</label>
                    </div>
                    <div>
                        <textarea id="commentTXT" rows="15" cols="60"></textarea>
                    </div>
                   

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">關閉</button>
                    <button id="submit" onclick="saveComment()" type="button" class="btn btn-primary">送出</button>
                </div>
            </div>
        </div>
    </div>
    </div>

    <script>
        var starRate;
                        $(function () {
                            // 星星評等
                            $("#div0").find("img").on({
                                mouseenter: function () {
                                    $(this).prop("src", "../Content/ProductPostImg/member/chngstar.jfif");
                                    $(this).prevAll().attr("src", "../Content/ProductPostImg/member/chngstar.jfif");
                                    $("#div0 p").text("評分為......." + ($(this).index() + 1) + "分，雙擊滑鼠送出");
               
                                },
                                mouseout: function () {
                                    $(this).prop("src", "../Content/ProductPostImg/member/star.jfif");
                                    $(this).nextAll().attr("src", "../Content/ProductPostImg/member/star.jfif")
                                }
                                ,
                                dblclick: function () {
                                    $("#div0").find("img").off("mouseenter");
                                    $("#div0").find("img").off("mouseout");
                                    $("#div0").off("mouseout");
                                    $("#div0 p").text("評分完成......" + ($(this).index() + 1) + "分");
                                    starRate = $(this).index() + 1;
                                },
                            });
                                $("#div0").mouseout(function () {
                                    $(this).children("img").prop("src", "../Content/ProductPostImg/member/star.jfif");
                                    $("#div0 p").text("評分中.......");
                                })
                         });

    //OrderID:3 獲得目前評價
        function getComment() {
        $.ajax({
            url: "@Url.Action("getComment","MyOrder")",
            data: { OrderDetailID:25},
            type: "GET",
            success: function (result) {
                var CNT = result.CNT;
                var starTotal = result.starTotal;
                var starAVG = 0;

                if (CNT==0)
                {
                    starAVG = 0;
                }
                else
                {
                    starAVG = starTotal / CNT;
                }
                console.log('result ',result);
                console.log("img",`${result.img}`);
                console.log("starTotal", `${result.starTotal}`);
                console.log("starAVG得分",`${starAVG}`);

                $("#commentCNT").text(`已經有${result.CNT}人評分`);
                $("#modal-body img").eq(0).attr("src", `../Content/ProductPostImg/member/${result.img}`);
                $("#progress-bar").css("width", `${starAVG * 20}%`).prop("aria-valuenow", `${starAVG}`).text(`${starAVG }`);
            },
        })
    }
     
        function saveComment() {
            console.log(starRate);
           
        $.ajax({
            url: "@Url.Action("saveComment", "MyOrder")",
            data: {  OrderID:"40", starRate: starRate, description: $(`#commentTXT`).val()},
            type: "GET",
            success: function (result) {
            swal('成功', '感謝您寶貴的意見', 'success');
                setTimeout(function () { $(".close").click() }, 700);
            },
            error: function(){
            swal("失敗","星星滿意度為必要勾選!!",'error');
            }
            })
            }


    </script>

Team4_maimai-master/MaiMai/MaiMai/Views/MyOrder/report.cshtml
@{
    ViewBag.Title = "report";

}

<style>

    input[type=radio] {
        display: none;
    }

    label {
        margin: 0 6px;
        margin-bottom: 20px;
    }
</style>
<div class="container " style="padding-top:100px; ">


    <h2>report</h2>


    <!-- Button trigger modal -->
    <img style="height:50px" src="https://www.flaticon.com/svg/vstatic/svg/1500/1500374.svg?token=exp=1615444750~hmac=5271c46b193004b97eac5b164883dddf" class="btn " data-toggle="modal" onclick="report()" data-target="#exampleModalCenter">

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title" id="exampleModalCenterTitle">檢舉內容</h2>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span id="modalSpan" aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">關閉</button>
                    <button id="submit" onclick="saveReport()" type="button" class="btn btn-primary">送出</button>
                </div>
            </div>
        </div>
    </div>

</div>


<script>

    function report() {
        $.ajax({
            url: "@Url.Action("getReport","MyOrder")",
            data: {},
            type: "GET",
            success: function (result) {
                $(".modal-body").html(`
                <!-- Default dropright button -->
<p>
  <a class="btn btn-danger" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    檢舉標籤
  </a>
</p>
<div class="collapse" id="collapseExample">
                <div  id="reportTags"class="btn-group">
                </div>
</div>



                <div id="warning" class="align-content-center">
                <label ><h3>內容描述</h3></label>
                </div>
                <div>
                <textarea id="reportTXT" rows="15" cols="60"></textarea>
                </div>
`);

                $.each(result, function (index, item) {
                    $("#reportTags").append(`
<input type="radio"class="btn btn-info " value="${index}"style="border-radius:50px"id="btnradio${index}" required>
  <label  for="btnradio${index}" class="btn btn-info " value="${index}"style="border-radius:50px" onclick="changeColor()" >
${item.reason}</label>
                `)
                })

            }
        })
    }

    function changeColor() {
        $(event.target).removeClass("btn-info").addClass("btn-success").siblings().removeClass("btn-success").addClass("btn-info");
    };

    function saveReport() {
        //var reportTAG = new Array();
        //$('input:checked').each(function (i) { reportTAG[i] = $(this).val(); });
        console.log(`reportTAG=$('input:checked').val()`);
        var reportTAG = $('input:checked').val() * 1 + 1;
        if (reportTAG == "NaN") {
            return false;
        }
        $.ajax({
            url: "@Url.Action("saveReport","MyOrder")",
            data: { reportTXT: $("#reportTXT").val(), reportTAG: reportTAG  },
            type: "POST",
            success: function (result) {
                swal('成功', '送出成功', 'success');
                setTimeout(function () { $(".close").click() }, 700);
            },
            error: function(){
                swal("失敗","檢舉標籤為必要勾選!!",'error');
            }
        })
    }

</script>

Team4_maimai-master/MaiMai/MaiMai/Views/MyOrder/shoppingCart.cshtml
@{
    ViewBag.Title = "shoppingCart";
}

<h2>shoppingCart</h2>

<div class="container">
    <div class="row col-8 justify-content-end">

    </div>
</div>

<script>
    $(function(){
        $.ajax({
            url: "@Url.Action("shoppingCart","MyOrder")",
            data: {orderID:???},
            type:"GET",
            success: function (result) {

                $("#show").html("<div class='d-flex justify-content-center' id='search'></div> <table class='table table-hover'><thead class='table-dark'><tr id='showTh'> <th>產品ID</th><th>產品名稱</th><th>會員等級</th><th>信箱</th><th>城市</th><th></th></tr></thead> <tbody id='showList'></tbody></table>");

                $(result).each(function (index,item) {
                    $("#showList").append(`<tr><td>${item.userAccount}</td><td>${item.Name}</td><td>${item.userLevel}</td><td>${item.email}</td><td>${item.city}</td><td><button type='button' class='btn btn-primary' data-toggle='modal' onclick='getMember(${item.UserID})' data-target='#editMember'>編輯</button></td></tr>`);    //刪除按鈕
                });
            }
        })

    });

</script>